repos:
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        name: Black
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        name: Flake
        language_version: python3
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.1.0
    hooks:
      - id: pip-compile
        name: UpdateProd
        stages: [ commit ]
        files: (^requirements/requirements\.(in|txt)$)
        #TODO: Remove no-emit flag once the package will be available on public pypi
        args: [ --output-file=requirements/requirements.txt, --quiet, --no-emit-index-url, requirements/requirements.in ]
        description: This hook updates requirements from requirements/requirements.in to requirements/requirements.txt

      - id: pip-compile
        name: UpdateDev
        stages: [ commit ]
        files: ^requirements/requirements_dev\.(in|txt)$
        #TODO: Remove no-emit flag once the package will be available on public pypi
        args: [ --output-file=requirements/requirements_dev.txt, --quiet, --no-emit-index-url,
                requirements/requirements.txt, requirements/requirements_dev.in ]
        description: This hook updates requirements from requirements/requirements_dev.in to requirements/requirements_dev.txt
