# syntax=docker/dockerfile:1

FROM python:{{PYTHON_VERSION}}-slim-buster

WORKDIR /app

COPY . .
RUN echo -e "{{PYTHON_VERSION}}\n{{PROJECT_NAME}}\n{{SRC}}\n{{PROJECT_DESCRIPTION}}\nn" | bash bin/init_repo.sh
RUN make init
RUN make reqs
RUN make setup

WORKDIR /app/{{SRC}}