# syntax=docker/dockerfile:1

FROM python:{{PYTHON_VERSION}}-slim-buster

WORKDIR /app

COPY requirements/requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

WORKDIR /app/{{SRC}}

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]